name: videollama3
channels:
  - defaults
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.10
  - pip
  - numpy=1.24.4
  - imageio=2.34.0
  - imageio-ffmpeg=0.4.9
  - moviepy=1.0.3
  - opencv
  - librosa
  - scikit-learn=1.2.2
  - huggingface_hub=0.23.4
  - sentencepiece=0.1.99
  - shortuuid
  - einops=0.6.1
  - pydantic>=2.0
  - markdown2
  - httpx=0.24.1
  - openai=1.33.0
  - requests
  - uvicorn
  - fastapi
  - tensorboard
  - wandb
  - tabulate
  - pip:
      - torch==2.5.0
      - torchaudio==2.5.0
      - torchvision==0.20.0
      - transformers==4.42.3
      - tokenizers==0.19.1
      - accelerate==0.26.1
      - peft==0.4.0
      - timm==1.0.3
      - decord==0.6.0
      - scenedetect==0.6.3
      - gradio==3.50.0
      - gradio_client==0.6.1
      - einops-exts==0.0.4
      - bitsandbytes==0.43.0
      - pytorchvideo